### ISSUE TITLE
Sort alphabetically the search engines installed in the context menu?

### ISSUE THREAD

**Issue by kimme** [benbasson/contextsearch#1]
There should be an option to have the search engines sorted alphabetically in the context menu, as they now default to the time they were installed...

**Comment by tumler100** [comment]
Searchbar window overflow. I have to many search bars for the search bar drop-down window. 
Manage search engines are no longer awailable. 
Earlier I used the first letter of the search engines names  to quickly select the search engine I wanted. Now I take a stab at some random candidate search engine, and hopes the label shown will be the one want to use for my search. 
My search engines have been sorted manually, but I should have the original firefox search bar. After the revision a few months ago I lost axess to a lot the engines I use regularly.
![my mozilla firefox search bar icon overflow](https://cloud.githubusercontent.com/assets/11854741/7047015/154ce274-de0a-11e4-8625-267bc8977afd.jpg)
