### ISSUE TITLE
Import/export ?

### ISSUE THREAD

**Issue by juju4** [benbasson/contextsearch#10]
Hello Ben and thanks a lot for this useful plugin.

Any plan to add an import/export feature?
Context Menu search on chrome (http://ashutoshdwivedi.com/2010/09/context-menu-search-for-chrome/) has a nice one which allow to sync different install and would be nice to have some cross-browser import/export :)

ex:
```
[["-1","DuckDuckGo","https://duckduckgo.com/?q=TESTSEARCH",true],["-1","Google","http://www.google.com/search?q=TESTSEARCH",true],["-1","Google Translate->EN","http://translate.google.com/#auto/en/TESTSEARCH",true],["-1","Bing","http://www.bing.com/search?q=TESTSEARCH",true]]
```

Thanks a lot

**Comment by benbasson** [comment]
Hi, thanks for your comments. I have no plans to add import / export - I'm aiming to keep Context Search as simple as possible, and that means relying on the in-built functionality of Firefox to manage the search plugins installed.
