### ISSUE TITLE
Search engine with login

### ISSUE THREAD

**Issue by rzsolt** [benbasson/contextsearch#13]
There are search engines which require login before a form can be used. It would be very helpful to be able to use those forms.

**Comment by benbasson** [comment]
Could you give me an example of one of these search engines? 

My gut feeling here is that this is a problem for the search engine to deal with. If you search using Context Search (or any other method) and you're not logged in, it should ask you to log in and then continue with your search. Once logged in, the search engine should remember you?

**Comment by rzsolt** [comment]
I use search engines which deliver paid info. Before being able to run a query, I must be logged in. The logged in status can be changed by logging out deliberately, by not using the service for some time and (in one case) by somebody (eg. me) trying to log in from an other IP address with the same credentials while logged in somewhere else.

The service I'm using now doesn't forward the query if I'm present a login screen instead of the query form, they just log me in, so I have to do the contextsearch twice in these cases, one for an unsuccessful search on the site, because the login screen appears, I login, then close that tab, and do the contextsearch again (being logged in in some seconds, the query will be successful).

Really not a big deal, just thinking of sparing that repetition... :-)

**Comment by benbasson** [comment]
I don't think there's really anything I can usefully do about that problem unfortunately. You may want to look around and see if there's an add-on that will automatically log you into a site, or something like that. All this add-on does is open a tab, using a search string that Firefox gives it. I don't think there's any way to add authentication to that.

**Comment by rzsolt** [comment]
Hi Ben,

Thank you for considering. And for the tool, I use it every day.

Best regards,

Zsolt
--

2016-12-24 1:40 GMT+01:00 Ben Basson <notifications@github.com>:
