### ISSUE TITLE
Context Search not showing up in context menu in Firefox 45.0b1 on OS X 10.11.3

### ISSUE THREAD

**Issue by betamod** [benbasson/contextsearch#17]
Context Search not showing up in context menu in Firefox 45.0b1 on OS X 10.11.3. Seems to have begun when I opened Firefox. 

Tried uninstalling and reinstalling Context Search extension but this did not fix it. 

Have not installed any new plugins or search engines in many months. Not sure what could have changed.

**Comment by frinnst** [comment]
Confirmed on 45.b2 on Linux

**Comment by frinnst** [comment]
relevant docs:
https://blog.mozilla.org/addons/2016/02/05/compatibility-for-firefox-45/
https://developer.mozilla.org/en-US/Firefox/Releases/45

**Comment by benbasson** [comment]
Is this still a problem?

**Comment by frinnst** [comment]
Not for me.
