### ISSUE TITLE
Can not be verified by Firefox

### ISSUE THREAD

**Issue by tomncar** [benbasson/contextsearch#21]
Hi, Firefox is telling me this can't be verified and will be stopped as an add-on in Firefox 43 (which will mean I don't upgrade as this is one of the most useful add-ons I have)
Please , I hope it's not too much hassle to have this verified with Mozilla.

All the best & many thanks for a brilliant adddon

**Comment by benbasson** [comment]
Hiya, I'm sure I've left it a little late to reply to this, but if you install the add-on from the Mozilla add-ons site, everything should work fine. This is still working for me in Firefox 50...
