### ISSUE TITLE
Not compatible with multiprocess

### ISSUE THREAD

**Issue by rmbleeker** [benbasson/contextsearch#23]
I didn't see a bug report for this yet, but I hope it's being worked on.
https://developer.mozilla.org/en-US/Add-ons/Working_with_multiprocess_Firefox

**Comment by bege10** [comment]
It is strange. The release note for 0.6.4 says it is compatible with multiprocess but my addon manager says the contrary.

**Comment by jeweloper** [comment]
I can confirm that v0.6.4 doesn't support electrolysis / multi-processes.
Tested with Firefox 50.0

**Comment by jeweloper** [comment]
Annotation: There is a fork that still supports multi-processes: [Link](https://addons.mozilla.org/en-US/firefox/addon/context-search-x/)

**Comment by benbasson** [comment]
To be clear, the 0.6.4 release note fixed an issue related to multiprocess Firefox, but that doesn't make it compatible with multiprocess.

To be properly compatible with multiprocess, I had started a rewrite of Context Search using the add-on SDK, but seeing as Mozilla will probably get rid of the SDK by the end of 2017 in favour of WebExtensions, I'm currently considering how to take this forward.

If I can figure out how to work around the SDK issues I'm having, I'll push that version out even if it only lives for a year.

**Comment by benbasson** [comment]
See also #27

**Comment by benbasson** [comment]
This add-on will either be completely rewritten or will cease to exist depending on Mozilla's API support in the near future. At the very least it will be disabled for some months following the release of Firefox 57.
