### ISSUE TITLE
Never opens in foreground tab

### ISSUE THREAD

**Issue by bege10** [benbasson/contextsearch#25]
No matter what settings I use in Firefox settings, contextsearch hidden settings and TabMixPlus settings and how I klick the selected text, contextsearch always opens the search results in a background tab (or a new window).
Contextsearch 0.6.4, Firefox 49.0.1, Windows 7 Professional 64 bit SP1

**Comment by benbasson** [comment]
This sounds like a TabMixPlus problem to me. Context Search uses the (older) XUL API to open a new tab, but neither that "API" nor this add-on have really changed in about 12 years.
