### ISSUE TITLE
Double-click would be awesome

### ISSUE THREAD

**Issue by embeh** [benbasson/contextsearch#26]
It would be really great (and speed up using your addon a lot) if we could simply double-click on a word and it would trigger the 'Highlight Word' function. 

Right now, we need to 1.) click word to select, 2.) rt-click to open menu, 3.) click on 'Highlight Word'

My suggestion is to roll these three steps into one: 1.) double-click on word to trigger 'Highlight Word'

**Comment by benbasson** [comment]
I think you meant to request this as an enhancement for [Context Highlight](https://github.com/benbasson/contexthighlight)?

**Comment by embeh** [comment]
Right! Sorry for posting in the wrong place. Will move it to Context Highlight.
