### ISSUE TITLE
Not compatible with Multiprocessor

### ISSUE THREAD

**Issue by johndfurlong** [benbasson/contextsearch#28]
Your site says that "Context Search 0.6.4 - 12/03/2016" was rewritten for compatibility with multi-process Firefox (Electrolysis).

about:addons  says that it's not compatible.

**Comment by aaz1887** [comment]
Add-on Compatibility Reporter 2.2.3
( https://addons.mozilla.org/es/firefox/addon/add-on-compatibility-reporter/ )
says : Not compatible with multiprocess

**Comment by AbuMaia** [comment]
I am seeing the same behaviour on my Firefox 54 and Context Search 0.6.4.

**Comment by benbasson** [comment]
This add-on will either be completely rewritten or will cease to exist depending on Mozilla's API support in the near future. At the very least it will be disabled for some months following the release of Firefox 57.
