### ISSUE TITLE
Update to support MultiProcess?

### ISSUE THREAD

**Issue by omperus** [benbasson/contextsearch#30]
Hello, i really like your addon but currently its not compatible with the new firefox multiprocess, do you think its possible to update it? Thanks.

**Comment by betamod** [comment]
Yes, I second that!  Please update this extension. It is, hands down, the most useful and frequently used of all my Firefox extensions.

**Comment by tomncar** [comment]
I 3rd, 4th and and 5th that PLEASE. PRETTY PLEASE.
Am using a Context Search but the search engines aren't listed in the 1st column. I wouldn't have updated Firefox if I'd known I was going to lose , probably my most used Add-ON
Many, Many Thanks

**Comment by benbasson** [comment]
This add-on will either be completely rewritten or will cease to exist depending on Mozilla's API support in the near future. At the very least it will be disabled for some months following the release of Firefox 57.

**Comment by Chealer** [comment]
I assume the actual issue this reports is lack of support for Firefox 57 and ulterior, which is tracked in ticket #33.
