### ISSUE TITLE
browsing issues

### ISSUE THREAD

**Issue by platinum2308** [benbasson/contextsearch#31]
When contextsearch is enabled it breaks the browsing on multiple websites. For example on ebay, the pages freeze when you click on items and the browser doesn't redirect you.  
You have to refresh manually to get redirected and it does that on many websites. I'm using last version of firefox (55.0.3)
Hope you can fix it because i'm using your great add-on for years now and i feel handicapped without it.

Thank you

**Comment by benbasson** [comment]
This add-on will either be completely rewritten or will cease to exist depending on Mozilla's API support in the near future. At the very least it will be disabled for some months following the release of Firefox 57.
