### ISSUE TITLE
Create contextsearch context menu item as first item in the list

### ISSUE THREAD

**Issue by shiretoko212** [benbasson/contextsearch#6]
Currently I have to use the menu editor addon to make the contextsearch menu item show up at the top of the context menu list.  I was wondering if you could make it possible for contextsearch to do this, either as default or as an option.  It's literally the only reason I use Menu Editor, and I would prefer it not to be necessary.

**Comment by spacedingo** [comment]
This can be achieved by a menu editor addon like
https://addons.mozilla.org/en-US/firefox/addon/s3menu-wizard/

**Comment by benbasson** [comment]
I'm happy for add-ons to stick to their stated purpose. Mine is for searching, the menu editor is for editing menus. I don't really want to blur those lines by adding loads of unnecessary functionality to my add-on, which I would then have to test and support, when someone out there is already serving that need (and probably better than I would).
