### ISSUE TITLE
Option to add highlighted text to clipboard

### ISSUE THREAD

**Issue by glynxpttle** [benbasson/contextsearch#7]
Found this extension to be really useful and it's on my list of always install add-ons.

When using it and heading of on an internet expedition I sometimes find the need to re-enter the text into a search field or other entry box some sites down the line.
I would find it useful to have the text I highlighted automatically placed in the clipboard for pasting at the time of the initial search.

Suggest maybe having it as a configurable option.

Thanks.

**Comment by spacedingo** [comment]
Try these
https://addons.mozilla.org/en-US/firefox/addon/autocopy-2/
https://addons.mozilla.org/en-US/firefox/addon/selectionsk/

**Comment by benbasson** [comment]
Thanks for commenting. This add-on is only concerned with search, not other activities like managing the clipboard. I agree with spacedingo and suggest you use one of those add-ons.
