### ISSUE TITLE
Default search engine and currently selected engine

### ISSUE THREAD

**Issue by relem** [benbasson/contextsearch#9]
One improvement the new FF search functionality provide was that; if you chose to use an search engine for a specific search, you could select, make your search and return to your default automatically.  This was seemingly helpful in that FF previously would bring up the last browser used as the default when starting up the next time.  The only problem is the case where you want to use that other browser for several searches in a row.  You have to select it each time.

One real improvement was a shortcut to an Options page for Search that provided the old manage your search engine capabilities and allowed you to set the default explicitly..

I much prefer your interface as I can simply read the names of my search engines to select.  I would suggest two improvements.  1. Incorporate setting the default engine explicitly.  2. Provide a means of resetting the search engine to the default when closing FF, rather than after every use of another engine.

**Comment by benbasson** [comment]
Those suggestions are good ideas, but I can't see how they fit into this add-on. All this add-on does is put search options on the context menu. It doesn't mess around with the default engine. If you have a problem with how the core browser search box works, I would suggest filing a bug with Mozilla for their consideration.
